# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'openweather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for openweather
  pod 'Alamofire', '~> 4.0'
  pod 'InLocoMedia-Ads-SDK', '~> 2.3.5'
  
  target 'openweatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'openweatherUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
